/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("application")
}

dependencies {
    implementation(project(":index"))
}

application {
    // Define the main class for the application.
    mainClass = "com.amitcul.app.App"
}
